### ISSUE TITLE
Costos y Juicios

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-equipo-ycej#2]
[Práctica 7.- Costos-Edwin_Yanet_Carlos_Jeronima.pdf](https://github.com/user-attachments/files/17542069/Practica.7.-.Costos-Edwin_Yanet_Carlos_Jeronima.pdf)

**Comment by Nelsy21** [comment]
Cumple con buena portada y los escudos institucionales: 25 puntos
Describe el procedimiento: 25 puntos
Incluye ilustraciones y capturas: 25 puntos
Conclusion: 25 puntos
Puntaje alcanzado 100% = 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
